src/Entity/Speciality.php
<?php

namespace App\Entity;

use App\Repository\SpecialityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: SpecialityRepository::class)]
class Speciality
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Regex("/^[A-Z][a-z]/")]
    #[Assert\Length(max:255)]
    #[Assert\Type(type:'string')]
    private ?string $speciality_name = null;

    #[ORM\OneToMany(mappedBy: 'speciality', targetEntity: User::class)]
    private Collection $users;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    #[Assert\Length(max : 255, maxMessage : "Description cannot be longer than {{ limit }} characters")]
    private ?string $description = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSpecialityName(): ?string
    {
        return $this->speciality_name;
    }

    public function setSpecialityName(string $speciality_name): self
    {
        $this->speciality_name = $speciality_name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setSpeciality($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSpeciality() === $this) {
                $user->setSpeciality(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->speciality_name;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/SpecialityType.php
<?php

namespace App\Form;

use App\Entity\Speciality;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpecialityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('speciality_name')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Speciality::class,
        ]);
    }
}

src/Controller/SpecialityController.php
<?php

namespace App\Controller;

use App\Entity\Speciality;
use App\Form\SpecialityType;
use App\Repository\SpecialityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/speciality')]
class SpecialityController extends AbstractController
{
    #[Route('/', name: 'app_speciality_index', methods: ['GET'])]
    public function index(SpecialityRepository $specialityRepository): Response
    {
        return $this->render('speciality/index.html.twig', [
            'specialities' => $specialityRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_speciality_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SpecialityRepository $specialityRepository): Response
    {
        $speciality = new Speciality();
        $form = $this->createForm(SpecialityType::class, $speciality);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $specialityRepository->save($speciality, true);

            return $this->redirectToRoute('app_speciality_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('speciality/new.html.twig', [
            'speciality' => $speciality,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_speciality_show', methods: ['GET'])]
    public function show(Speciality $speciality): Response
    {
        return $this->render('speciality/show.html.twig', [
            'speciality' => $speciality,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_speciality_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Speciality $speciality, SpecialityRepository $specialityRepository): Response
    {
        $form = $this->createForm(SpecialityType::class, $speciality);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $specialityRepository->save($speciality, true);

            return $this->redirectToRoute('app_speciality_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('speciality/edit.html.twig', [
            'speciality' => $speciality,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_speciality_delete', methods: ['POST'])]
    public function delete(Request $request, Speciality $speciality, SpecialityRepository $specialityRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$speciality->getId(), $request->request->get('_token'))) {
            $specialityRepository->remove($speciality, true);
        }

        return $this->redirectToRoute('app_speciality_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/speciality/_delete_form.html.twig
<form method="post" action="{{ path('app_speciality_delete', {'id': speciality.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ speciality.id) }}">
    <button class="btn">Delete</button>
</form>

templates/speciality/_form.html.twig
{% extends 'backComp.html.twig' %}
{% block main %}
{{ form_start(form,{'attr':{'novalidate':'novalidate'}})}}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
{% endblock %}

templates/speciality/edit.html.twig
{% extends 'backComp.html.twig' %}

{% block title %}Edit Speciality{% endblock %}

{% block main %}
    <h1>Edit Speciality</h1>

    {{ include('speciality/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_speciality_index') }}">back to list</a>

    {{ include('speciality/_delete_form.html.twig') }}
{% endblock %}

templates/speciality/index.html.twig
{% extends 'backComp.html.twig' %}

{% block title %}Speciality index{% endblock %}

{% block main %}
    <h1>Speciality index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Speciality_name</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for speciality in specialities %}
            <tr>
                <td>{{ speciality.id }}</td>
                <td>{{ speciality.specialityName }}</td>
                <td>{{ speciality.description }}</td>

                <td>
                    <a href="{{ path('app_speciality_show', {'id': speciality.id}) }}">show</a>
                    <a href="{{ path('app_speciality_edit', {'id': speciality.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_speciality_new') }}">Create new</a>
{% endblock %}

templates/speciality/new.html.twig
{% extends 'backComp.html.twig' %}

{% block title %}New Speciality{% endblock %}

{% block main %}
    <h1>Create new Speciality</h1>

    {{ include('speciality/_form.html.twig') }}

    <a href="{{ path('app_speciality_index') }}">back to list</a>
{% endblock %}

templates/speciality/show.html.twig
{% extends 'backComp.html.twig' %}

{% block title %}Speciality{% endblock %}

{% block main %}
    <h1>Speciality</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ speciality.id }}</td>
            </tr>
            <tr>
                <th>Speciality_name</th>
                <td>{{ speciality.specialityName }}</td>
            </tr>
              <tr>
                <th>Description</th>
                <td>{{ speciality.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_speciality_index') }}">back to list</a>

    <a href="{{ path('app_speciality_edit', {'id': speciality.id}) }}">edit</a>

    {{ include('speciality/_delete_form.html.twig') }}
{% endblock %}